/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

/**
 *
 * @author Carlos
 */
public class Principal extends javax.swing.JFrame {

    /** Creates new form Principal */
    public Principal() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo1 = new javax.swing.JLabel();
        Ttiulo2 = new javax.swing.JLabel();
        BTNxFranquicias = new javax.swing.JButton();
        BTNxEstrenos = new javax.swing.JButton();
        BTNxProductora = new javax.swing.JButton();
        BtnConsultas = new javax.swing.JButton();
        BTNxTitulos = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(575, 372));
        setMinimumSize(new java.awt.Dimension(575, 372));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        Titulo1.setText("Consultas");
        getContentPane().add(Titulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 80, 40));

        Ttiulo2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        Ttiulo2.setText("CRUDs");
        getContentPane().add(Ttiulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 80, 40));

        BTNxFranquicias.setText("Franquicia");
        getContentPane().add(BTNxFranquicias, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 100, 30));

        BTNxEstrenos.setText("Estreno/Rango");
        getContentPane().add(BTNxEstrenos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 150, 30));

        BTNxProductora.setText("Productora");
        getContentPane().add(BTNxProductora, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 100, 30));

        BtnConsultas.setText("Consultas Varias");
        getContentPane().add(BtnConsultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 150, 30));

        BTNxTitulos.setText("Titulos");
        getContentPane().add(BTNxTitulos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 100, 30));

        jButton2.setText("Actualizar");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 140, 30));

        jButton3.setText("Borrar");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 140, 30));

        jButton4.setText("Crear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, 140, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        CRUD_Create nv =new CRUD_Create();
        nv.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNxEstrenos;
    private javax.swing.JButton BTNxFranquicias;
    private javax.swing.JButton BTNxProductora;
    private javax.swing.JButton BTNxTitulos;
    private javax.swing.JButton BtnConsultas;
    private javax.swing.JLabel Titulo1;
    private javax.swing.JLabel Ttiulo2;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    // End of variables declaration//GEN-END:variables

}
